services:
  lb:
    build: .
    command: -p 8080 10.5.0.5:80 
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - "8000:8080"
  web:
    image: "nginx:alpine"
    ports:
      - "8080:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  client: 
    image: "docker.arvancloud.ir/alpine:latest"
    command: sleep infinity
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

